# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9LVOgAwn8Ec5bHMoQrnVRJuZvPaUjwe
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
import pandas as pd
import numpy as np
from pickle import dump, load
import sklearn
#from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer

print('The scikit-learn version is {}.'.format(sklearn.__version__))

data = pd.read_csv("finalcropdata.csv")

x = data.drop(["District","Year","Yield"],axis=1)
y = data["Yield"]

x_train = data.drop(["District","Year","Yield"],axis=1).values
y_train = data["Yield"].values

print(x_train)
print(y_train)

pipeline = Pipeline(steps=[('scale', MinMaxScaler()), ('model',RandomForestRegressor(n_estimators=500,random_state=42,))])

model = TransformedTargetRegressor(regressor=pipeline, transformer=MinMaxScaler())

model.fit(x_train,y_train)

dump(model,open("model.pkl","wb"))

data2 = pd.read_csv("finalcroptest.csv")

x = data2.drop(["District","Year","Yield"],axis=1)
y = data2["Yield"]
print(x)
# x_test = np.array(x)
# y_test = np.array(y)
# x_test

model1 = load(open("model.pkl","rb"))
ans = model1.predict(x)

metrics.r2_score(ans,y)

list(map(float,ans[:10]))

ex_ans = [25,5478,612,98920,734000]

data = [[5,2,1,22.10667,25,19],
        [17,1,1,29.004833,756.711,6384],
        [32,1,1,30.483667,683.394,5529],
        [13,2,2,-1.329833,194.9,52842],
        [25,2,2,19.3675,79.2,171000]]

# data = sc.transform(data)

ans = model.predict(data)



print(list(map(float,ans)))

#db.run(port=8050)
